重构suggest函数
RF-Tar-Railt/nonebot-plugin-waiter pull request #6
Opened 2024-08-05 09:34 UTC by kzqj

2024-08-05 09:38 UTC, kzqj commented on README.md
> +| waiter_suggest_hint | 否 | - {suggest} | 默认建议信息的提示
这个配置项和使用的地方应该做下修改？ 没有`{suggest}`占位会出错

2024-08-05 12:44 UTC, RF-Tar-Railt requested changes

2024-08-05 12:44 UTC, RF-Tar-Railt commented on README.md
> +resp = await suggest_in("请选择xxx", ["a", "b", "c", "d"])
改回去

2024-08-05 12:44 UTC, RF-Tar-Railt commented on src/nonebot_plugin_waiter/__init__.py
> +async def suggest_(
用_suggest

2024-08-05 12:44 UTC, RF-Tar-Railt commented on src/nonebot_plugin_waiter/__init__.py
> +async def suggest_in(
改回去

2024-08-05 12:44 UTC, RF-Tar-Railt commented on src/nonebot_plugin_waiter/__init__.py
>  async def suggest_not_in(
用suggest_not或者not_suggest

2024-08-05 12:44 UTC, RF-Tar-Railt commented on src/nonebot_plugin_waiter/__init__.py
> +    )
如果是非候选项，那可以不用换行

2024-08-05 13:35 UTC, kzqj commented on src/nonebot_plugin_waiter/__init__.py
> +    )
没明白你意思，这样输出不行吗
```python
>>> XX已存在，请输入新的XX
    以下为非候选项
    - a
    - b
    - c
    - d
```

2024-08-15 04:09 UTC, RF-Tar-Railt approved these changes

2024-08-15 04:10 UTC, merged